services:
  db:
    image: postgres:14
    container_name: db
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    restart: always
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
    ports:
      - 5432:5432
  
  app:
    image: monitoring
    restart: always

    